In [18]:
import pandas as pd
df = pd.read_csv(r"C:\Users\SHIVA\DESKTOP\cybersecurity data\global cs threats\Global_Cybersecurity_Threats_2015-2024.csv")
df.head()

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Country                              3000 non-null   str
 1   Year                                 3000 non-null   int64
 2   Attack Type                          3000 non-null   str
 3   Target Industry                      3000 non-null   str
 4   Financial Loss (in Million $)        3000 non-null   float64
 5   Number of Affected Users             3000 non-null   int64
 6   Attack Source                        3000 non-null   str
 7   Security Vulnerability Type          3000 non-null   str
 8   Defense Mechanism Used               3000 non-null   str
 9   Incident Resolution Time (in Hours)  3000 non-null   int64
dtypes: float64(1), int64(3), str(6)
memory usage: 234.5 KB

In [20]:
# check missing values
df.isnull().sum()

Country                                0
Year                                   0
Attack Type                            0
Target Industry                        0
Financial Loss (in Million $)          0
Number of Affected Users               0
Attack Source                          0
Security Vulnerability Type            0
Defense Mechanism Used                 0
Incident Resolution Time (in Hours)    0
dtype: int64

In [21]:
# clean column  names and remove duplicates
df.columns = df.columns.str.strip()
df = df.drop_duplicates()

In [22]:
# Summary statistics using .describe()
df. describe(include='all')

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
count,3000,3000.000000,3000,3000,3000.000000,3000.000000,3000,3000,3000,3000.000000
unique,10,NaN,6,7,NaN,NaN,4,4,5,NaN
top,UK,NaN,DDoS,IT,NaN,NaN,Nation-state,Zero-day,Antivirus,NaN
freq,321,NaN,531,478,NaN,NaN,794,785,628,NaN
mean,NaN,2019.570333,NaN,NaN,50.492970,504684.136333,NaN,NaN,NaN,36.476000
std,NaN,2.857932,NaN,NaN,28.791415,289944.084972,NaN,NaN,NaN,20.570768
min,NaN,2015.000000,NaN,NaN,0.500000,424.000000,NaN,NaN,NaN,1.000000
25%,NaN,2017.000000,NaN,NaN,25.757500,255805.250000,NaN,NaN,NaN,19.000000
50%,NaN,2020.000000,NaN,NaN,50.795000,504513.000000,NaN,NaN,NaN,37.000000
75%,NaN,2022.000000,NaN,NaN,75.630000,758088.500000,NaN,NaN,NaN,55.000000
max,NaN,2024.000000,NaN,NaN,99.990000,999635.000000,NaN,NaN,NaN,72.000000

In [23]:
# Renaming columns according to snake casing for better readability and documentation
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [24]:
df.columns

Index(['country', 'year', 'attack_type', 'target_industry',
       'financial_loss_(in_million_$)', 'number_of_affected_users',
       'attack_source', 'security_vulnerability_type',
       'defense_mechanism_used', 'incident_resolution_time_(in_hours)'],
      dtype='str')

In [25]:
df.info()
df.isnull()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              3000 non-null   str
 1   year                                 3000 non-null   int64
 2   attack_type                          3000 non-null   str
 3   target_industry                      3000 non-null   str
 4   financial_loss_(in_million_$)        3000 non-null   float64
 5   number_of_affected_users             3000 non-null   int64
 6   attack_source                        3000 non-null   str
 7   security_vulnerability_type          3000 non-null   str
 8   defense_mechanism_used               3000 non-null   str
 9   incident_resolution_time_(in_hours)  3000 non-null   int64
dtypes: float64(1), int64(3), str(6)
memory usage: 234.5 KB

,country,year,attack_type,target_industry,financial_loss_(in_million_$),number_of_affected_users,attack_source,security_vulnerability_type,defense_mechanism_used,incident_resolution_time_(in_hours)
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False,False
2996,False,False,False,False,False,False,False,False,False,False
2997,False,False,False,False,False,False,False,False,False,False
2998,False,False,False,False,False,False,False,False,False,False
2999,False,False,False,False,False,False,False,False,False,False

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              3000 non-null   str
 1   year                                 3000 non-null   int64
 2   attack_type                          3000 non-null   str
 3   target_industry                      3000 non-null   str
 4   financial_loss_(in_million_$)        3000 non-null   float64
 5   number_of_affected_users             3000 non-null   int64
 6   attack_source                        3000 non-null   str
 7   security_vulnerability_type          3000 non-null   str
 8   defense_mechanism_used               3000 non-null   str
 9   incident_resolution_time_(in_hours)  3000 non-null   int64
dtypes: float64(1), int64(3), str(6)
memory usage: 234.5 KB

In [28]:
# Rename columns
df = df.rename(columns={
    'security_vulnerability_type': 'vulnerability_type',
    'defense_mechanism_used': 'defense_mechanism',
    'financial_loss_(in_million_$)': 'financial_loss_m',
    'incident_resolution_time_(in_hours)': 'resolution_time_h',
    'number_of_affected_users': 'affected_users',
    
})

print(df.columns.tolist())

['country', 'year', 'attack_type', 'target_industry', 'financial_loss_m', 'affected_users', 'attack_source', 'vulnerability_type', 'defense_mechanism', 'resolution_time_h']

In [35]:
# checking what type of attacks are there and how many times it occurred
print(df['attack_type'].value_counts())
print(df['attack_type'].unique())

attack_type
DDoS                 531
Phishing             529
SQL Injection        503
Ransomware           493
Malware              485
Man-in-the-Middle    459
Name: count, dtype: int64
<StringArray>
[         'Phishing',        'Ransomware', 'Man-in-the-Middle',
              'DDoS',     'SQL Injection',           'Malware']
Length: 6, dtype: str

In [37]:
#  Creating new column with simple names for attacks for dashboard - easy for anyone to understand
attack_map_pro = {
    'Phishing': 'Email Fraud',
    'Ransomware': 'Data Lock',
    'DDoS': 'Site Closed',
    'SQL Injection': 'Database Attack',
    'Malware': 'virus Attack',
    'Man-in-the-Middle': 'Message Stolen'
}

df['attack_category'] = df['attack_type'].map(attack_map_pro)

print(df['attack_category'].value_counts())

attack_category
Site Closed        531
Email Fraud        529
Database Attack    503
Data Lock          493
virus Attack       485
Message Stolen     459
Name: count, dtype: int64

In [72]:
# Creating new column with simple names
attack_map_pro = {
    'Zero-day': 'Unknown Bug',
    'Social Engineering': 'people Tricked',
    'Unpatched Software': 'System Not Updated',
    'Weak Passwords': 'Weak Password'
}

df['vulnerability_category'] = df['vulnerability_type'].map(attack_map_pro)

print(df['vulnerability_category'].value_counts())

vulnerability_category
Unknown Bug           785
people Tricked        747
System Not Updated    738
Weak Password         730
Name: count, dtype: int64

In [85]:
print(df.columns.tolist())

['country', 'year', 'attack_type', 'target_industry', 'financial_loss_m', 'affected_users', 'attack_source', 'vulnerability_type', 'defense_mechanism', 'resolution_time_h', 'attack_category', 'vulnerability_category', 'loss_severity', 'resolution_speed']

In [86]:
def get_severity(x):
    if x > 50:
        return 'high'
    elif x >= 20:
        return 'moderate'
    else:
        return 'low'

df['loss_severity'] = df['financial_loss_m'].apply(get_severity)

In [87]:
df['resolution_speed'] = df['resolution_time_h'].apply(lambda x: 'Fast' if x < 24 else 'Slow')

In [88]:
print(df.columns.tolist())

['country', 'year', 'attack_type', 'target_industry', 'financial_loss_m', 'affected_users', 'attack_source', 'vulnerability_type', 'defense_mechanism', 'resolution_time_h', 'attack_category', 'vulnerability_category', 'loss_severity', 'resolution_speed']

In [89]:
df.head()

,country,year,attack_type,target_industry,financial_loss_m,affected_users,attack_source,vulnerability_type,defense_mechanism,resolution_time_h,attack_category,vulnerability_category,loss_severity,resolution_speed
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63,Email Fraud,System Not Updated,high,Slow
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71,Data Lock,System Not Updated,high,Slow
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20,Message Stolen,Weak Password,moderate,Fast
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7,Data Lock,people Tricked,moderate,Fast
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68,Message Stolen,people Tricked,high,Slow

In [91]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: C:\Users\SHIVA\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [92]:
from sqlalchemy import create_engine

#step1: connect to postgresql
username = "postgres"
password = "password"
host = "localhost"
port = "65535"
database = "cyber_threat"
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step2
table_name = "cyber"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'cyber' in database 'cyber_threat'.